package iqutils

import (
	"flag"
	"log"
	"os"
)

type QKDRuntime struct {
	certificate string
	privateKey  string
	kme         string
	sae         string
	keyID       string
	Debug       bool
	Quiet       bool
}

var qkdRuntime QKDRuntime

var cert = flag.String("certificate", os.Getenv("QKD_CLIENT_CERTIFICATE"), "Patch to the QKD client certificate")
var key = flag.String("privatekey", os.Getenv("QKD_CLIENT_PRIVATE_KEY"), "Path to the QKD client private key")

var sae = flag.String("qkd-sae", os.Getenv("QKD_SAE"), "Name of the target SAE")
var kmeURL = flag.String("qkd-kme", os.Getenv("QKD_KME"), "URL for the QKD KME endpoint")
var keyid = flag.String("qkd-keyid", os.Getenv("QKD_KEYID"), "(optional) ID for the QKD key generated by KME")

var cdebug = flag.Bool("debug", false, "Enable debug mode")
var cquiet = flag.Bool("quiet", false, "Enable quiet mode")

var debug bool
var quiet bool

func ArgsValidator() QKDRuntime {
	flag.Parse()
	if *cert == "" || *key == "" {
		log.Fatalf("[!!] Both certificate and private key must be provided.")
		flag.Usage()
	} else {
		_, err := os.Stat(*cert)
		if err != nil {
			log.Fatalf("[!!] Invalid certificate path [%s]\n", *cert)
		}
		_, err = os.Stat(*key)
		if err != nil {
			log.Fatalf("[!!] Invalid private key path [%s]\n", *key)
		}
	}

	if *sae == "" {
		log.Fatalf("[!!] QKD SAE short name must be provided.")
		flag.Usage()
	}

	if *kmeURL == "" {
		log.Fatalf("[!!] QKD KME endpoint must be provided.")
		flag.Usage()
	}

	debug = *cdebug
	quiet = *cquiet

	qkdRuntime = QKDRuntime{
		certificate: *cert,
		privateKey:  *key,
		kme:         *kmeURL,
		sae:         *sae,
		keyID:       *keyid,
		Debug:       *cdebug,
		Quiet:       *cquiet,
	}

	return qkdRuntime
}
